# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

variables:
  # Map pipeline secrets to variables used by tests. Set these as secret variables in the pipeline UI or variable group.
  - name: INTERNXT_TEST_EMAIL
    value: $(INTERNXT_TEST_EMAIL)
  - name: INTERNXT_TEST_PASSWORD
    value: $(INTERNXT_TEST_PASSWORD)
  - name: INTERNXT_TEST_2FA_SECRET
    value: $(INTERNXT_TEST_2FA_SECRET)
  - name: DESKTOP_HEADER
    value: $(DESKTOP_HEADER)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build'

- script: npm test
  displayName: 'Run tests'
  env:
    INTERNXT_TEST_EMAIL: $(INTERNXT_TEST_EMAIL)
    INTERNXT_TEST_PASSWORD: $(INTERNXT_TEST_PASSWORD)
    INTERNXT_TEST_2FA_SECRET: $(INTERNXT_TEST_2FA_SECRET)
    DESKTOP_HEADER: $(DESKTOP_HEADER)

# Publish to npm only when previous steps succeeded. Requires a pipeline variable/secret named NPM_TOKEN
- script: |
    echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    npm publish --access public
  displayName: 'Publish to npm'
  env:
    NPM_TOKEN: $(NPM_TOKEN)
  condition: succeeded()
