name: Integration Tests

on:
  workflow_dispatch:
  schedule:
    # Run integration tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Run unit tests
        run: npm run test:unit
        env:
          CI: true
      
      - name: Run integration tests
        run: npm run test:integration
        env:
          CI: true
          INTERNXT_TEST_EMAIL: ${{ secrets.INTERNXT_TEST_EMAIL }}
          INTERNXT_TEST_PASSWORD: ${{ secrets.INTERNXT_TEST_PASSWORD }}
          INTERNXT_TEST_2FA_SECRET: ${{ secrets.INTERNXT_TEST_2FA_SECRET }}
          DESKTOP_HEADER: ${{ secrets.DESKTOP_HEADER || '3b68706a367fd567b929396290b1de40768bb768' }}
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test/fixtures/
            *.log
          retention-days: 7
